apiVersion: v1
kind: Service
metadata:
  name: addressbook-loadbalancer
  labels:
    app: production
spec:
  tyoe: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: addressbook-pods #must match with deployment app name-->app name from addressbook-deployment.yaml#