apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: httpd-deployment  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd-container
          image: httpd
          ports:
            - containerPort: 80