apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  type: NodePort
  selector:
    app: green # Points to the blue or green deployment initially
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080